### ISSUE TITLE
RFE: Provide a mechanism to check all transactions on a given identifier

### ISSUE THREAD

**Issue by amarts** [dhiway/cord#100]
Usecase: Anyone using 'chain' should be able to query the chain to see all transactions on the identifier. This would enhance the trust factor by multiple factor.

Can be implemented through pallet storage, or through a rpc method. 

Right now, the projects like subql which can aggregate all events on the chain build a query for such things, but still, that becomes a request served from an entity outside of the chain, and hence outside the purview of chain governance. This is key in 'verification' of any data.

**Comment by NiranjanAP** [comment]
with latest sparknet version, this is now done:

<img width="1275" alt="image" src="https://github.com/dhiway/cord/assets/3840787/234536fe-5115-4938-9052-251349de8f3b">
