### ISSUE TITLE
About static cord binary's dependency

### ISSUE THREAD

**Issue by amarts** [dhiway/cord#177]
Below is the error I got when I ran the cord binary build on ubuntu-22.04 (in ec2) on a debian machine on GCP.

```
amar@cord-test-1:~$ ./cord-static-x86-ubuntu key generate-node-key --file ./data/node-key
./cord-static-x86-ubuntu: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by ./cord-static-x86-ubuntu)
./cord-static-x86-ubuntu: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./cord-static-x86-ubuntu)
./cord-static-x86-ubuntu: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./cord-static-x86-ubuntu)
./cord-static-x86-ubuntu: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./cord-static-x86-ubuntu)
./cord-static-x86-ubuntu: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./cord-static-x86-ubuntu)
```

Highlight is, we surely need `libc` to be of same version on machines where it is build. Hence when we publish artefacts, we should make sure to name it properly with `arch` used, and also `libc` version.

**Comment by roynrishingha** [comment]
Our current binary release from the Github action forces us to use ubuntu-22.04 OS on a x84_64 architecture. So to support any other architecture we can either use our docker image or release more binaries to cover other OS and Architectures.

**Comment by NiranjanAP** [comment]
Closing this issue as it is duplicated with https://github.com/dhiway/cord/issues/226 with C4GT format
