### ISSUE TITLE
Replace mentions of the `ci-linux:production` image tag with the `ci-unified:latest`

### ISSUE THREAD

**Issue by rcny** [dhiway/cord#188]
Hello everyone!

I see that your project uses one of the `paritytech` CI images. Just FYI, the `paritytech/ci-linux:production` image has been deprecated in favor of [the `paritytech/ci-unified` image](https://github.com/paritytech/scripts/tree/master/dockerfiles/ci-unified). Please use the `paritytech/ci-unified:latest` image in your workflows, pipelines or docs, or use the specific tag (e.g. `paritytech/ci-unified:bullseye-1.70.0`) for granularity and versioning, but you will still need to check upstream for new releases.

**Comment by roynrishingha** [comment]
Hello @rcny 
Thanks for pointing it out. Can you please provide more information regarding this issue?

**Comment by roynrishingha** [comment]
Thanks @rcny for pointing it out. Will look into it and fix.
