### ISSUE TITLE
[C4GT] Understand the logs and find remedy

### ISSUE THREAD

**Issue by NiranjanAP** [dhiway/cord#224]
## Description

Sometimes after restart of the nodes (on validator) see below logs:

2023-08-15 17:07:38 Ignoring request to disconnect reserved peer 12D3KooWExU7gjGWPPPhUSHfRw2VNeej5wB4hQBkpomvYiMntrj1 from SetId(2).    
2023-08-15 17:07:39 Trying to disconnect unknown peer 12D3KooWBJktXVM6URUUoDKUxdU2hTxq5d57BzRWt4VCf5ivh4CP from SetId(0).    
2023-08-15 17:07:39 Ignoring request to disconnect reserved peer 12D3KooWBJktXVM6URUUoDKUxdU2hTxq5d57BzRWt4VCf5ivh4CP from SetId(1).    
2023-08-15 17:07:39 Ignoring request to disconnect reserved peer 12D3KooWBJktXVM6URUUoDKUxdU2hTxq5d57BzRWt4VCf5ivh4CP from SetId(2).    
Need to understand when and why these logs come up.

## Goals
- [ ] Understand the reason for the logs and report, suggest a remedy

## Expected Outcome
- [ ] Report the reason for the logs
- [ ] Suggest a remedy

## Acceptance Criteria
- [ ] Remedy should be tried out and demonstrated to be working fine

## Implementation Details
NA

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts @NiranjanAP 

## Complexity
Low

## Category
Bug

## Sub Category
Beginner friendly

**Comment by Harsh1s** [comment]
Hi there, the reason behind these logs is one of the packages being used, namely `substrate`. Older versions of `substrate` had this issue. The issue keeps happening even later, but the log is suspended by moving it to debug layer.

You can review these pull requests:
https://github.com/paritytech/substrate/pull/14406
https://github.com/paritytech/substrate/pull/14274

The remedy that I propose is that we should update `substrate` and its dependencies to the latest version.
I'd like to work on this issue so can you please assign it to me?

**Comment by smohan-dw** [comment]
@Harsh1s  This is already fixed.

**Comment by Harsh1s** [comment]
> @Harsh1s This is already fixed.

No worries then. Still out of curiosity, I'd like to know the remedy and how close I was to it. If it's not a bother, could you please tell me?
