### ISSUE TITLE
statement: missing tests for error `InvalidIdentifierLength`

### ISSUE THREAD

**Issue by amarts** [dhiway/cord#278]
No tests for `InvalidIdentifierLength` error condition in `pallets/statement/src/tests.rs`

Look at other test cases, and add a test case for the same.

Subtask under : https://github.com/cord-network/community/issues/7

New testcase can be tested under `cargo test -p pallet-statement` after adding it in the code.

**Comment by hardik-pratap-singh** [comment]
Hey @amarts !
I would like to work on this issue. Kindly assign it to me.
