### ISSUE TITLE
[C4GT] Identity: Add tests for `RegistrarAlreadyExists`

### ISSUE THREAD

**Issue by vatsa287** [dhiway/cord#289]
## Description
Subtask under : https://github.com/cord-network/community/issues/7

New testcase can be tested under `cargo test -p pallet-identity` after adding it in the code.

## Goals

- [ ] Add tests for `RegistrarAlreadyExists` for pallet/identity

## Expected Outcome
- [ ] Test should assert for `RegistrarAlreadyExists` being returned properly in all the possible calls.
- [ ] If there are more than one function returning this error code, all of them should be validated either as one test case or as multiple test cases.
       
## Acceptance Criteria
NA

## Implementation Details
Look at other test cases, and add a test case for the same.
Ex: `uninvited_judgement_should_work` which validates error code `RegistrarNotFound`

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts 

## Complexity
[Low]

## Category
[Test]

## Sub Category
[Beginner friendly]

**Comment by priyakumari02** [comment]
Hello @vatsa287 , Can  I work on this issue?

**Comment by vatsa287** [comment]
@priyakumari02 Yes you can. Please raise a PR for the ticket you're interested in working on, even if it hasn't been assigned to you. Since it's first-come, first-served on a PR basis.
You can refer PR #325. Go through the README for setup and pre PR checks.

**Comment by Sriramkashyapks** [comment]
Please assign this issue to me

**Comment by VedantKhairnar** [comment]
@vatsa287 
If the contribution to this issue is done, will you pls close it? Thanks.

**Comment by vatsa287** [comment]
@VedantKhairnar Sure!
