### ISSUE TITLE
  [C4GT] Network-Membership: Add tests for `MembershipNotFound`

### ISSUE THREAD

**Issue by vatsa287** [dhiway/cord#291]
## Description
Subtask under : https://github.com/cord-network/community/issues/7

New testcase can be tested under `cargo test -p pallet-network-membership` after adding it in the code.

## Goals

- [ ] Add tests for `MembershipNotFound` for pallet/network-membership.

## Expected Outcome
- [ ] Test should assert for `MembershipNotFound` being returned properly in all the possible calls.
- [ ] If there are more than one function returning this error code, all of them should be validated either as one test case or as multiple test cases.
       
## Acceptance Criteria
NA

## Implementation Details
Look at other test cases, and add a test case for the same.
Ex: `test_duplicate_member_request` which validates error code `MembershipAlreadyAcquired`

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts 

## Complexity
[Medium]

## Category
[Test]

## Sub Category
[Beginner friendly]

**Comment by shravankshenoy** [comment]
Hi, I would like to work on this issue

**Comment by Ris-code** [comment]
Hello, I would like to contribute to this issue. Could you please assign me this?

**Comment by VedantKhairnar** [comment]
Hello @Ris-code 
Do you need any assistance with the issue or any progress you might want to share?
Thanks.
