### ISSUE TITLE
 [C4GT] Network-Membership: Add tests for `MembershipRenewalAlreadyRequested`

### ISSUE THREAD

**Issue by vatsa287** [dhiway/cord#292]
## Description
Subtask under : https://github.com/cord-network/community/issues/7

New testcase can be tested under `cargo test -p pallet-network-membership` after adding it in the code.

## Goals

- [ ] Add tests for `MembershipRenewalAlreadyRequested` for pallet/network-membership

## Expected Outcome
- [ ] Test should assert for `MembershipRenewalAlreadyRequested` being returned properly in all the possible calls.
- [ ] If there are more than one function returning this error code, all of them should be validated either as one test case or as multiple test cases.
       
## Acceptance Criteria
NA

## Implementation Details
Look at other test cases, and add a test case for the same.
Ex: `test_duplicate_member_request` which validates error code `MembershipAlreadyAcquired`

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts 

## Complexity
[Low]

## Category
[Test]

## Sub Category
[Beginner friendly]

**Comment by priyakumari02** [comment]
Hello @vatsa287 , Can I work on this issue?

**Comment by vatsa287** [comment]
@priyakumari02 Yes you can! Please refer PR #325.
