### ISSUE TITLE
 [C4GT] Network-Score: Add tests for 'InvalidIdentifierLength'

### ISSUE THREAD

**Issue by vatsa287** [dhiway/cord#295]
## Description
Subtask under : https://github.com/cord-network/community/issues/7

New testcase can be tested under `cargo test -p pallet-network-score` after adding it in the code.

## Goals

- [ ] Add tests for `InvalidIdentifierLength` for pallet/network-score

## Expected Outcome
- [ ] Test should assert for `InvalidIdentifierLength` being returned properly in all the possible calls.
- [ ] If there are more than one function returning this error code, all of them should be validated either as one test case or as multiple test cases.
       
## Acceptance Criteria
NA

## Implementation Details
Look at other test cases, and add a test case for the same.
Ex: In pallets/network-membership check method `test_duplicate_member_request` which validates error code `MembershipAlreadyAcquired`

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts 

## Complexity
[Low]

## Category
[Test]

## Sub Category
[Beginner friendly]

**Comment by hardik-pratap-singh** [comment]
Hey @amarts
I would like to work on this issue ! 
Please assign it to me if possible.

**Comment by PayalKumari10** [comment]
Hello @vatsa287 @amarts, I want to work on this project
Can you assign this issue to me?
