### ISSUE TITLE
 [C4GT] Network-Score: Add tests for 'InvalidRatingValue' 

### ISSUE THREAD

**Issue by vatsa287** [dhiway/cord#297]
## Description
Subtask under : https://github.com/cord-network/community/issues/7

New testcase can be tested under `cargo test -p pallet-network-score` after adding it in the code.

## Goals

- [ ] Add tests for `InvalidRatingValue` for pallet/network-score

## Expected Outcome
- [ ] Test should assert for `InvalidRatingValue` being returned properly in all the possible calls.
- [ ] If there are more than one function returning this error code, all of them should be validated either as one test case or as multiple test cases.
       
## Acceptance Criteria
NA

## Implementation Details
Look at other test cases, and add a test case for the same.
Ex: In pallets/network-membership check method `test_duplicate_member_request` which validates error code `MembershipAlreadyAcquired`

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts 

## Complexity
[Agree]

## Category
[Test]

## Sub Category
[Beginner friendly]

**Comment by Sanika-k-1317** [comment]
Hello @vatsa287
I am interested in contributing to this project. Can we please connect for further discussions and could you please asssign the ticket to me?

**Comment by heyhimansh** [comment]
Hi @vatsa287 ,
Could you assign me the task of adding tests for 'InvalidRatingValue' in the Network-Score project?

**Comment by VedantKhairnar** [comment]
Hello @Sanika-k-1317 
Are you working on the issue?
Pls let us know if you need any assistance. 
Thanks.

Meanwhile, @heyhimansh Are you interested in working on the issue?

**Comment by vatsa287** [comment]
Closing as completed from PR
https://github.com/dhiway/cord/pull/507
