### ISSUE TITLE
 [C4GT] Network-Score: Add tests for 'RatingIdentifierAlreadyAdded'

### ISSUE THREAD

**Issue by vatsa287** [dhiway/cord#298]
## Description
Subtask under : https://github.com/cord-network/community/issues/7

New testcase can be tested under `cargo test -p pallet-network-score` after adding it in the code.

## Goals

- [ ] Add tests for `RatingIdentifierAlreadyAdded` for pallet/network-score

## Expected Outcome
- [ ] Test should assert for `RatingIdentifierAlreadyAdded` being returned properly in all the possible calls.
- [ ] If there are more than one function returning this error code, all of them should be validated either as one test case or as multiple test cases.
       
## Acceptance Criteria
NA

## Implementation Details
Look at other test cases, and add a test case for the same.
Ex: In pallets/network-membership check method `test_duplicate_member_request` which validates error code `MembershipAlreadyAcquired`

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts 

## Complexity
[Low]

## Category
[Test]

## Sub Category
[Beginner friendly]

**Comment by vatsa287** [comment]
Implement this error code `RatingIdentitfierAlreadyExists` also for the following methods,
- [ ] revoke_rating()
- [ ] revise_rating()

Contributors can refer this [PR](https://github.com/dhiway/cord/pull/392/files).

**Comment by zeel991** [comment]
I would like to complete the issue @vatsa287

**Comment by hardik-pratap-singh** [comment]
Hello @amarts @vatsa287 , 
Please assign me this issue as referenced in #294.

**Comment by vatsa287** [comment]
@hardik-pratap-singh @zeel991 Please take up one each and complete.

**Comment by hardik-pratap-singh** [comment]
@zeel991 I am working on "revoke_rating()"
