### ISSUE TITLE
 [C4GT] Network-Score: Add tests for `RatingIdentifierNotFound`

### ISSUE THREAD

**Issue by vatsa287** [dhiway/cord#300]
## Description
Subtask under : https://github.com/cord-network/community/issues/7

New testcase can be tested under `cargo test -p pallet-network-score` after adding it in the code.

## Goals

- [ ] Add tests for `RatingIdentifierNotFound` for pallet/network-score

## Expected Outcome
- [ ] Test should assert for `RatingIdentifierNotFound` being returned properly in all the possible calls.
- [ ] If there are more than one function returning this error code, all of them should be validated either as one test case or as multiple test cases.
       
## Acceptance Criteria
NA

## Implementation Details
Look at other test cases, and add a test case for the same.
Ex: In pallets/network-membership check method `test_duplicate_member_request` which validates error code `MembershipAlreadyAcquired`

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts 

## Complexity
[Low]

## Category
[Test]

## Sub Category
[Beginner friendly]

**Comment by Sanika-k-1317** [comment]
Hello @vatsa287
I am interested in contributing to this project. Can we please connect for further discussions and could you please asssign the ticket to me?

**Comment by vatsa287** [comment]
Hi @Sanika-k-1317  Welcome. You can work on this issue. You can refer other PRs of C4GT. Also can connect through C4GTs discord channel.

**Comment by PayalKumari10** [comment]
Hello @vatsa287 @amarts, I want to work on this project
Can you assign this issue to me?
