### ISSUE TITLE
 [C4GT] Network-Score: Add tests for `ReferenceIdentifierNotFound`

### ISSUE THREAD

**Issue by vatsa287** [dhiway/cord#301]
## Description
Subtask under : https://github.com/cord-network/community/issues/7

New testcase can be tested under `cargo test -p pallet-network-score` after adding it in the code.

## Goals

- [ ] Add tests for `ReferenceIdentifierNotFound` for pallet/network-score

## Expected Outcome
- [ ] Test should assert for `ReferenceIdentifierNotFound` being returned properly in all the possible calls.
- [ ] If there are more than one function returning this error code, all of them should be validated either as one test case or as multiple test cases.
       
## Acceptance Criteria
NA

## Implementation Details
Look at other test cases, and add a test case for the same.
Ex: In pallets/network-membership check method `test_duplicate_member_request` which validates error code `MembershipAlreadyAcquired`

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts 

## Complexity
[Medium]

## Category
[Test]

## Sub Category
[Beginner friendly]

**Comment by Jhanvi528** [comment]
Hey @vatsa287 sir I would love to work on this project.. Please assign this to me if possible

**Comment by VedantKhairnar** [comment]
Hello @Jhanvi528 
if you are open to contributing, pls directly raise the PR.
Thanks.

**Comment by JiyaGupta-cs** [comment]
@vatsa287  @amarts @VedantKhairnar Can you please review the PR
