### ISSUE TITLE
 [C4GT] Network-Score: Add tests for `EntityMismatch`

### ISSUE THREAD

**Issue by vatsa287** [dhiway/cord#303]
## Description
Subtask under : https://github.com/cord-network/community/issues/7

New testcase can be tested under `cargo test -p pallet-network-score` after adding it in the code.

## Goals

- [ ] Add tests for `EntityMismatch` for pallet/network-score

## Expected Outcome
- [ ] Test should assert for `EntityMismatch` being returned properly in all the possible calls.
- [ ] If there are more than one function returning this error code, all of them should be validated either as one test case or as multiple test cases.
       
## Acceptance Criteria
NA

## Implementation Details
Look at other test cases, and add a test case for the same.
Ex: In pallets/network-membership check method `test_duplicate_member_request` which validates error code `MembershipAlreadyAcquired`

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts 

## Complexity
[Low]

## Category
[Test]

## Sub Category
[Beginner friendly]

**Comment by hardiksharma11** [comment]
Hii @vatsa287 
I would like to contribute to it as a good first issue. Could you assign me this...
