### ISSUE TITLE
 [C4GT] Node-Authorization: Add tests for `InvalidUtf8`

### ISSUE THREAD

**Issue by vatsa287** [dhiway/cord#307]
## Description
Subtask under : https://github.com/cord-network/community/issues/7

New testcase can be tested under `cargo test -p pallet-node-authorization` after adding it in the code.

## Goals

- [ ] Add tests for `InvalidUtf8` for pallet/network-authorization

## Expected Outcome
- [ ] Test should assert for `InvalidUtf8` being returned properly in all the possible calls.
- [ ] If there are more than one function returning this error code, all of them should be validated either as one test case or as multiple test cases.
       
## Acceptance Criteria
NA

## Implementation Details
Look at other test cases, and add a test case for the same.
Ex: check method `add_well_known_node_works` which validates error code `NodeIdTooLong`

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts 

## Complexity
[Medium]

## Category
[Test]

## Sub Category
[Beginner friendly]

**Comment by Anushreebasics** [comment]
@vatsa287 @amarts I am a beginner but I want to work on this issue,please guide me

**Comment by glitchdoescode** [comment]
@vatsa287 @amarts  assign this subtask to me, I wanna complete it

**Comment by dhruvk-01** [comment]
@vatsa287 @amarts Can you please assign this task to me?

**Comment by hp77-creator** [comment]
Hi @vatsa287 I do not see any `network-authorization` directory in `pallet`, I think the description for this issue should be updated to `node-authorization`

**Comment by vatsa287** [comment]
> Hi @vatsa287 I do not see any `network-authorization` directory in `pallet`, I think the description for this issue should be updated to `node-authorization`

Thanks for pointing this out. Will change it.
