### ISSUE TITLE
 [C4GT] Network-Authorization: Add tests for `AlreadyConnected`

### ISSUE THREAD

**Issue by vatsa287** [dhiway/cord#309]
## Description
Subtask under : https://github.com/cord-network/community/issues/7

New testcase can be tested under `cargo test -p pallet-network-authorization` after adding it in the code.

## Goals

- [ ] Add tests for `AlreadyConnected` for pallet/network-authorization

## Expected Outcome
- [ ] Test should assert for `AlreadyConnected` being returned properly in all the possible calls.
- [ ] If there are more than one function returning this error code, all of them should be validated either as one test case or as multiple test cases.
       
## Acceptance Criteria
NA

## Implementation Details
Look at other test cases, and add a test case for the same.
Ex: check method `add_well_known_node_works` which validates error code `NodeIdTooLong`

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts 

## Complexity
[Low]

## Category
[Test]

## Sub Category
[Beginner friendly]

**Comment by milinddethe15** [comment]
I am working on this.
