### ISSUE TITLE
 [C4GT] Schema: Add tests for `InvalidIdentifierLength`

### ISSUE THREAD

**Issue by vatsa287** [dhiway/cord#311]
## Description
Subtask under : https://github.com/cord-network/community/issues/7

New testcase can be tested under `cargo test -p pallet-schema` after adding it in the code.

## Goals

- [ ] Add tests for `InvalidIdentifierLength` for pallet/schema

## Expected Outcome
- [ ] Test should assert for `InvalidIdentifierLength` being returned properly in all the possible calls.
- [ ] If there are more than one function returning this error code, all of them should be validated either as one test case or as multiple test cases.
       
## Acceptance Criteria
NA

## Implementation Details
Look at other test cases, and add a test case for the same.
Ex: check method `check_duplicate_schema_creation` which validates error code `SchemaAlreadyAnchored`

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts 

## Complexity
[Low]

## Category
[Test]

## Sub Category
[Beginner friendly]

**Comment by ayerhssb** [comment]
Greetings, @vatsa287 @amarts  - I've understood the issue and I would like to collaborate on this issue.

**Comment by PriyaD17** [comment]
Hey @vatsa287 and @amarts, in this project we have to make a test that asserts for invalid identifier length and we need to add this test to pallets/schema/src/tests.rs path that should pass the Cargo test. Have I got the right idea? let me know if I am wrong otherwise please assign me this issue so I can start working on it.
Thankyou

**Comment by vatsa287** [comment]
@PriyaD17 Yes the idea is right. 
But you can pick any other issues ex. https://github.com/dhiway/cord/issues/379 which is also a good first issue.
As `IdentifierLength` related tests are not required as they predefined upper bound set at compile time.

**Comment by tanishkagupta27** [comment]
Hey @vatsa287,  I'm confident in my understanding of the problem and possess the necessary skills. I'd be grateful for the opportunity to be assigned to this project.

**Comment by vatsa287** [comment]
@tanishkagupta27 You can take a look at this. 
https://github.com/dhiway/cord/issues/283
Please comment there if you are interested. 
This will be closed due my previous comment.
