### ISSUE TITLE
 [C4GT] Statement: Add tests for `StatementAlreadyAnchored`

### ISSUE THREAD

**Issue by vatsa287** [dhiway/cord#313]
## Description
Subtask under : https://github.com/cord-network/community/issues/7

New testcase can be tested under `cargo test -p pallet-statement` after adding it in the code.

## Goals

- [ ] Add tests for `StatementAlreadyAnchored` for pallet/statement

## Expected Outcome
- [ ] Test should assert for `StatementAlreadyAnchored` being returned properly in all the possible calls.
- [ ] If there are more than one function returning this error code, all of them should be validated either as one test case or as multiple test cases.
       
## Acceptance Criteria
NA

## Implementation Details
Look at other test cases, and add a test case for the same.
Ex: check method `trying_to_register_statement_by_a_non_delegate_should_fail` which validates error code `UnauthorizedOperation`

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts 

## Complexity
[Low]

## Category
[Test]

## Sub Category
[Beginner friendly]

**Comment by priyakumari02** [comment]
Hi @vatsa287 , Can I work on this issue?
