### ISSUE TITLE
 [C4GT] Statement: Add tests for `StatementRevoked`

### ISSUE THREAD

**Issue by vatsa287** [dhiway/cord#314]
## Description
Subtask under : https://github.com/cord-network/community/issues/7

New testcase can be tested under `cargo test -p pallet-statement` after adding it in the code.

## Goals

- [ ] Add tests for `StatementRevoked` for pallet/statement

## Expected Outcome
- [ ] Test should assert for `StatementRevoked` being returned properly in all the possible calls.
- [ ] If there are more than one function returning this error code, all of them should be validated either as one test case or as multiple test cases.
       
## Acceptance Criteria
NA

## Implementation Details
Look at other test cases, and add a test case for the same.
Ex: check method `trying_to_update_a_non_registered_statement_should_fail` which validates error code `StatementNotFound`

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts 

## Complexity
[Low]

## Category
[Test]

## Sub Category
[Beginner friendly]

**Comment by Sriramkashyapks** [comment]
Issue #314: Adding Tests for StatementRevoked

Dear vatsa287 , as a beginner contributor, I'm eager to take on issue #314. I'm motivated to learn, dedicated to the project's standards, and see this as a valuable learning opportunity. Please consider assigning it to me. Thank you.

Best, Sriram Kashyap

**Comment by vatsa287** [comment]
@Sriramkashyapks Welcome! You can start working on this and send the PR. You can have a reference with #342.

**Comment by ninja-mayank** [comment]
@vatsa287 , as a beginner I am interested to take on issue #314. I have gone through the code and am confident that I can resolve it. Please consider assigning it to me. Thank you

**Comment by vatsa287** [comment]
@ninja-mayank Welcome! I see a open PR for this already. If possible you can send PR for anything which has no PR submitted yet.

**Comment by Sayanjones** [comment]
@vatsa287 I'm interested on this project. Can we discuss further?

**Comment by rising0raj** [comment]
Hey @vatsa287 I would like to work on this . I have gone through the code base can you assign this to me if it is open??

**Comment by Yashhatwar22** [comment]
Hey, @vatsa287  I'm a beginner, I have gone through the code base, would like to work on this , Can you assign it if it is open?

**Comment by vatsa287** [comment]
> @ninja-mayank Welcome! I see a open PR for this already. If possible you can send PR for anything which has no PR submitted yet.

@Yashhatwar22 @rising0raj @Sayanjones ^^

**Comment by Gaurang3110** [comment]
@vatsa287 
Hello sir , i am eager to contribute to this project and also as a beginner , it will help me to start learning about different stuffs and will also play a major role in my starting phase.
so can you please assign this to me ?

**Comment by g-nitin-1** [comment]
@vatsa287
Hello Sir, I am a beginner in rust Programming language can you provide any resource to learn Rust programming language

**Comment by Sohajawdekar** [comment]
Hey @vatsa287 ! I am interested in working on this project and reviewed the codes and prerequisites. Can you please assign this issue to me ?

**Comment by 26vanshika** [comment]
Hey @vatsa287, I am interested to work upon this issue pls assign me
