### ISSUE TITLE
 [C4GT] Statement: Add tests for `InvalidIdentifierLength`

### ISSUE THREAD

**Issue by vatsa287** [dhiway/cord#316]
## Description
Subtask under : https://github.com/cord-network/community/issues/7

New testcase can be tested under `cargo test -p pallet-statement` after adding it in the code.

## Goals

- [ ] Add tests for `InvalidIdentifierLength` for pallet/statement

## Expected Outcome
- [ ] Test should assert for `InvalidIdentifierLength` being returned properly in all the possible calls.
- [ ] If there are more than one function returning this error code, all of them should be validated either as one test case or as multiple test cases.
       
## Acceptance Criteria
NA

## Implementation Details
Look at other test cases, and add a test case for the same.
Ex: check method `trying_to_register_statement_by_a_non_delegate_should_fail` which validates error code `UnauthorizedOperation`

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts 

## Complexity
[Medium]

## Category
[Test]

## Sub Category
[Beginner friendly]

**Comment by rising0raj** [comment]
Hey @vatsa287 I would like to work on this . I have gone through the code base can you assign this to me if it is open???

**Comment by Gaurang3110** [comment]
Hey @vatsa287 sir I would love to work on this project.. Please assign this to me if possible

**Comment by Sanika-k-1317** [comment]
Hello @vatsa287 
I am interested in contributing to this project. Can we please connect for further discussions and could you please asssign the ticket to me?

**Comment by Sohajawdekar** [comment]
Hey @vatsa287 !
I would like to contribute to this project, can you please assign this issue to me ?
