### ISSUE TITLE
 [C4GT] Statement: Add tests for `BulkTransactionFailed`

### ISSUE THREAD

**Issue by vatsa287** [dhiway/cord#317]
## Description
Subtask under : https://github.com/cord-network/community/issues/7

New testcase can be tested under `cargo test -p pallet-statement` after adding it in the code.

## Goals

- [ ] Add tests for `BulkTransactionFailed` for pallet/statement

## Expected Outcome
- [ ] Test should assert for `BulkTransactionFailed` being returned properly in all the possible calls.
- [ ] If there are more than one function returning this error code, all of them should be validated either as one test case or as multiple test cases.
       
## Acceptance Criteria
NA

## Implementation Details
Look at other test cases, and add a test case for the same.
Ex: check method `trying_to_register_statement_by_a_non_delegate_should_fail` which validates error code `UnauthorizedOperation`

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts 

## Complexity
[Low]

## Category
[Test]

## Sub Category
[Beginner friendly]

**Comment by ninja-mayank** [comment]
Hello @vatsa287 , I would like to take on issue #317. I see this as a great opportunity to learn. Please consider assigning it to me. Thank you

**Comment by vatsa287** [comment]
@ninja-mayank I see a open PR for this issue already. It would be great if you pick and get assigned on ones which is not being worked on currently.
