### ISSUE TITLE
 [C4GT] Statement: Add tests for `PresentationNotFound`

### ISSUE THREAD

**Issue by vatsa287** [dhiway/cord#319]
## Description
Subtask under : https://github.com/cord-network/community/issues/7

New testcase can be tested under `cargo test -p pallet-statement` after adding it in the code.

## Goals

- [ ] Add tests for `PresentationNotFound` for pallet/statement

## Expected Outcome
- [ ] Test should assert for `PresentationNotFound` being returned properly in all the possible calls.
- [ ] If there are more than one function returning this error code, all of them should be validated either as one test case or as multiple test cases.
       
## Acceptance Criteria
NA

## Implementation Details
Look at other test cases, and add a test case for the same.
Ex: check method `trying_to_register_statement_by_a_non_delegate_should_fail` which validates error code `UnauthorizedOperation`

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts 

## Complexity
[Low]

## Category
[Test]

## Sub Category
[Beginner friendly]

**Comment by Sweetdevil144** [comment]
Hey @vatsa287. I'm picking this issue and will come up with a PR for the same soon !!

**Comment by vatsa287** [comment]
@Sweetdevil144 sure go ahead! 
You can go through [PR](https://github.com/dhiway/cord/pull/325) for reference.

**Comment by Sweetdevil144** [comment]
Hey @vatsa287 , I've been creating tests but I think I'll need to assume some dummy values for the current function as follow :

```rust
#[test]
fn add_presentation_non_existent_statement_should_fail() {
    new_test_ext().execute_with(|| {
        // Can we create a function to generate a dummy statement id and digest as below to mock this?
        let statement_id = get_dummy_statement_id();
        let presentation_digest = get_dummy_presentation_digest();
        let presentation_type = get_dummy_presentation_type();
        let authorization_id = get_dummy_authorization_id();

        assert_err!(
            Statement::add_presentation(
                RawOrigin::Root.into(),
                statement_id,
                presentation_digest,
                presentation_type,
                authorization_id,
            ),
            Error::<Test>::StatementNotFound
        );
    });
}
```
Can you explain me a bit more of how this function may be important so as to avoid the current `dummy values` issue?

**Comment by rising0raj** [comment]
Hey @vatsa287 I would like to work on this . I have gone through the code base can you assign this to me if it is open??

**Comment by 26vanshika** [comment]
hey @vatsa287 Can you assign me this issue I am interested in it

**Comment by vatsa287** [comment]
@26vanshika @rising0raj Can look at this [issue](https://github.com/dhiway/cord/issues/298) too.
