### ISSUE TITLE
 [C4GT] Statement: Add tests for `StatementDigestAlreadyAnchored`

### ISSUE THREAD

**Issue by vatsa287** [dhiway/cord#320]
## Description
Subtask under : https://github.com/cord-network/community/issues/7

New testcase can be tested under `cargo test -p pallet-statement` after adding it in the code.

## Goals

- [ ] Add tests for `StatementDigestAlreadyAnchored` for pallet/statement

## Expected Outcome
- [ ] Test should assert for `StatementDigestAlreadyAnchored` being returned properly in all the possible calls.
- [ ] If there are more than one function returning this error code, all of them should be validated either as one test case or as multiple test cases.
       
## Acceptance Criteria
NA

## Implementation Details
Look at other test cases, and add a test case for the same.
Ex: check method `trying_to_register_statement_by_a_non_delegate_should_fail` which validates error code `UnauthorizedOperation`

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts 

## Complexity
[Low]

## Category
[Test]

## Sub Category
[Beginner friendly]

**Comment by huzaifmalik786** [comment]
Greetings, @vatsa287 , I would like to work on this issue. Can you guide me through this and assign the issue to me?

**Comment by vatsa287** [comment]
@huzaifmalik786  Yes you can raise the PR.
You can refer the PR #325. 

Go through the README for setup & pre-PR checks.

**Comment by huzaifmalik786** [comment]
I'm working on it.
