### ISSUE TITLE
When `cord` is built with `--features=runtime-benchmarks`, `did` signing does not work

### ISSUE THREAD

**Issue by vatsa287** [dhiway/cord#348]
When cord is built with `cargo build --profile=production --features=runtime-benchmarks`
& run the binary `./target/production/cord --dev --pruning=archive`. 

SDK methods are not executable with issues stating `BadOrigin`.

**Comment by smohan-dw** [comment]
This is because only remark pallet is enabled with DID calls when compiled with the runtime-benchmarks feature. Not an issue, it works as intended.

**Comment by smohan-dw** [comment]
https://github.com/dhiway/cord/blob/be78821ae7917e41dedc995f4825177210e93c55/runtime/src/lib.rs#L963

**Comment by vatsa287** [comment]
@smohan-dw Thank you for clarifying. Will close as completed.
