### ISSUE TITLE
[C4GT] Asset: Add tests for UnauthorizedOperation

### ISSUE THREAD

**Issue by vatsa287** [dhiway/cord#368]
## Description
Subtask under : https://github.com/cord-network/community/issues/7

New testcase can be tested under `cargo test -p pallet-asset` after adding it in the code.

## Goals

- [ ] Add tests for `UnauthorizedOperation` for pallet/asset

## Expected Outcome
- [ ] Test should assert for `UnauthorizedOperation` being returned properly in all the possible calls.
- [ ] If there are more than one function returning this error code, all of them should be validated either as one test case or as multiple test cases.
       
## Acceptance Criteria
NA

## Implementation Details
Look at other test cases, and add a test case for the same.
Ex: check method `asset_create_should_succeed` which validates creation of asset.

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts @vatsa287 

## Complexity
[Medium]

## Category
[Test]

## Sub Category
[Beginner friendly]

**Comment by ninja-mayank** [comment]
Hello @vatsa287 , I would like to contribute to ticket #368, Can you please assign it to me

**Comment by VishnuAmit** [comment]
Hey @vatsa287 I have raised a PR. Kindly look into it.

**Comment by Om-Thorat** [comment]
Hey @vatsa287 @amarts, I would like to work on this Issue. I have observed all the ways `UnauthorizedOperation` could be returned in pallet/asset and have also looked at other relevant tests for the same functions such as `asset_create_should_succeed` and setup & compiled the project on local.

Do let me know if i can start working on it :)

**Comment by vatsa287** [comment]
@Om-Thorat Sure you can take this up.
