### ISSUE TITLE
[C4GT] Asset: Add tests for `AssetIdAlreadyExists`

### ISSUE THREAD

**Issue by vatsa287** [dhiway/cord#371]
## Description
Subtask under : https://github.com/cord-network/community/issues/7

New testcase can be tested under `cargo test -p pallet-asset` after adding it in the code.

## Goals

- [ ] Add tests for `AssetIdAlreadyExists` for pallet/asset

## Expected Outcome
- [ ] Test should assert for `AssetIdAlreadyExists` being returned properly in all the possible calls.
- [ ] If there are more than one function returning this error code, all of them should be validated either as one test case or as multiple test cases.
       
## Acceptance Criteria
NA

## Implementation Details
Look at other test cases, and add a test case for the same.
Ex: check method `asset_create_should_succeed` which validates creation of asset.

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts @vatsa287 

## Complexity
[Low]

## Category
[Test]

## Sub Category
[Beginner friendly]

**Comment by ninja-mayank** [comment]
Hello @vatsa287 , I would like to work on ticket #371, Can you please assign it to me?
