### ISSUE TITLE
[C4GT] Asset: Add tests for `AssetIdNotFound`

### ISSUE THREAD

**Issue by vatsa287** [dhiway/cord#375]
## Description
Subtask under : https://github.com/cord-network/community/issues/7

New testcase can be tested under `cargo test -p pallet-asset` after adding it in the code.

## Goals

- [ ] Add tests for `AssetIdNotFound` for pallet/asset

## Expected Outcome
- [ ] Test should assert for `AssetIdNotFound` being returned properly in all the possible calls.
- [ ] If there are more than one function returning this error code, all of them should be validated either as one test case or as multiple test cases.
       
## Acceptance Criteria
NA

## Implementation Details
Look at other test cases, and add a test case for the same.
Ex: check method `asset_create_should_succeed` which validates creation of asset.

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts @vatsa287 

## Complexity
[Low]

## Category
[Test]

## Sub Category
[Beginner friendly]

**Comment by aishalxgupta** [comment]
Hi @vatsa287 
I'm confident in my understanding of the problem and possess the necessary skills. I'd be grateful for the opportunity to be assigned to this project

**Comment by vatsa287** [comment]
Hi @aishalxgupta Welcome. You can work on this issue. You can refer other PRs of C4GT. Also can connect through C4GTs discord channel.

**Comment by vatsa287** [comment]
Closing as completed.
