### ISSUE TITLE
[C4GT] Asset: Add tests for `InstanceNotActive`

### ISSUE THREAD

**Issue by vatsa287** [dhiway/cord#377]
## Description
Subtask under : https://github.com/cord-network/community/issues/7

New testcase can be tested under `cargo test -p pallet-asset` after adding it in the code.

## Goals

- [ ] Add tests for `InstanceNotActive` for pallet/asset

## Expected Outcome
- [ ] Test should assert for `InstanceNotActive` being returned properly in all the possible calls.
- [ ] If there are more than one function returning this error code, all of them should be validated either as one test case or as multiple test cases.
       
## Acceptance Criteria
NA

## Implementation Details
Look at other test cases, and add a test case for the same.
Ex: check method `asset_create_should_succeed` which validates creation of asset.

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts @vatsa287 

## Complexity
[Medium]

## Category
[Test]

## Sub Category
[Beginner friendly]

**Comment by Sriramkashyapks** [comment]
please assign this issue to me

**Comment by summerpun2803** [comment]
@vatsa287  can i work on this issue?

**Comment by VedantKhairnar** [comment]
Hello @vatsa287 
If the PR is merged for this issue, can we close this one?
Thanks.

**Comment by vatsa287** [comment]
Closing as completed from #483.
