### ISSUE TITLE
Multi-Runtime configuration with smart contracts support

### ISSUE THREAD

**Issue by smohan-dw** [dhiway/cord#457]
- [x] Multi-Runtime
   - [x] Braid - Permissioned Enterprise Runtime (1-sec blocktime)
   - [x] Loom - Permissioned Consortium/Ecosystem Runtime with Governance and Payments (3-sec blocktime)
- [x] Ink Smart Contracts 
- [ ] Chain Extensions
    - [ ] Identifier
    - [ ] Network Membership
- [x] Permissioned Authorities refactor
- [x] Update tests and test utils for multi-runtime
- [x] Update Chain Space 
- [ ] Refactor - Identity & Did
- [ ] Refactor - Did Name -> Identifier Name
- [x] Chain Spec Updates

**Comment by vatsa287** [comment]
@smohan-dw Can I try `Update Chain Space`? Where I would remove chain space tx limits for `loom` runtime config.
Approach: Use 2 chain-spaces `braid_chain_space`, `loom_chain_space`. Depending on the runtime, will use the required chain space.

**Comment by amarts** [comment]
My observation: Let us bring balance (or asset) from the upstream into everything. Just that we don't need to make that part of 'decision' making in choosing the validators (specially in `braid` and `loom`).  That way, the code always would use the similar stack other than for network-membership part of the pallet.

**Comment by smohan-dw** [comment]
> @smohan-dw Can I try `Update Chain Space`? Where I would remove chain space tx limits for `loom` runtime config. Approach: Use 2 chain-spaces `braid_chain_space`, `loom_chain_space`. Depending on the runtime, will use the required chain space.

We now have a permissioned flag in place. Check out pallet-config and the isPermissioned trait. We can use that within the pallet to decide the options. The permissionless chain space does not require the approval process, and the transaction limit should be kept at 0. A limit of zero means unlimited capacity.
